name: quickgui
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.8-1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  window_size: 
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 03d957e8b5c99fc83cd4a781031b154ab3de8753
  quiver: ^3.0.1+1
  tuple: ^2.0.0
  file_picker: ^6.1.1
  shared_preferences: ^2.0.8
  package_info_plus: ^5.0.1
  provider: ^6.0.1
  intl: ^0.18.0
  gettext: ^1.2.0
  gettext_parser: ^0.2.0
  flutter_localizations: 
    sdk: flutter
  desktop_notifications: ^0.6.1
  flutter_svg: ^2.0.9
  gettext_i18n: ^1.0.2
  url_launcher: ^6.1.6
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/i18n/
    - assets/quickemu-icons/
